### ISSUE TITLE
using length of optional target for reconstruction

### ISSUE THREAD

**Issue by 5ke** [Enny1991/beamformers#2]
Thank you for making your repository available.

For the MVDR and MSNR beamformers (in beamformers.py), the target is optional, but at the same time it is required to reconstruct the wave form. Wouldn't it be an option to obtain the length from the mixture instead?

**Comment by Enny1991** [comment]
Yes absolutely, this is actually a bug that I solved already locally, let me push it.

**Comment by 5ke** [comment]
Thanks!
