### ISSUE TITLE
Using beamform for multichannel recordings of sound clip

### ISSUE THREAD

**Issue by aristosp** [Enny1991/beamformers#4]
Hello, my name is Aris. Having seen the other issues, my question is this:
I have been instructed to use beamforming in order to make four channel sound clips of human activities into one, but I fail to understand where the noise component comes in. Is it possible to use beamforming in order to merge the four channels into one without having the noise?

Thank you very much in advance.

**Comment by Enny1991** [comment]
Hey Aris,

Generally speaking, this toolbox is to use beamforming as a way of filtering out noise or unwanted sounds sources. But I guess it could be used also to just "fuse" multi microphone recording into one. You can probably just give a zero matrix for the noise, but it could be numerically unstable, so just try with a matrix full of 1e-15 or so.

**Comment by aristosp** [comment]
I will try your recommendation, thanks alot!
